//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public Nullable<int> FK_UserId { get; set; }
        public Nullable<int> FK_PostId { get; set; }
        public Nullable<int> FK_SharedPostId { get; set; }
        public string Comment_Text { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Shared_Post Shared_Post { get; set; }
        public virtual User_Details User_Details { get; set; }
    }
}
