//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int likeId { get; set; }
        public int postId { get; set; }
        public System.Guid userId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User_Details User_Details { get; set; }
    }
}
