//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile_Views
    {
        public int Id { get; set; }
        public Nullable<int> FK_UserId { get; set; }
        public Nullable<int> Viewer_UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual User_Details User_Details { get; set; }
        public virtual User_Details User_Details1 { get; set; }
    }
}
