//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shared_Post
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public Nullable<int> post_id { get; set; }
        public System.Guid Sharing_UserId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User_Details User_Details { get; set; }
    }
}
